const SET_LAND_SUCCESS = 'SET_LAND_SUCCESS'
const SET_LAUNCH_YEAR = 'SET_LAUNCH_YEAR'
const SET_LAUNCH_SUCCESS = 'SET_LAUNCH_SUCCESS'

export {
    SET_LAND_SUCCESS,
    SET_LAUNCH_YEAR,
    SET_LAUNCH_SUCCESS,
}

